### ISSUE TITLE
Login timeout expired connecting to serverless Azure SQL Database when paused

### ISSUE THREAD

**Issue by revodavid** [r-dbi/odbc#289]
Not sure if this is an error in `odbc` or in Azure SQL Database, but if you are using [serverless mode](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-serverless) and the database has auto-paused, creating the connection fails:

```R
> constr="
Driver={SQL Server};Server=tcp:REDACTED.database.windows.net,1433;Database=retail;Uid=REDACTED@REDACTED;Pwd=REDACTED;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
"
> con <- dbConnect(odbc(), .connection_string=constr)
Error: nanodbc/nanodbc.cpp:950: HYT00: [Microsoft][ODBC SQL Server Driver]Login timeout expired 
```

The workaround is to wait 10-20 seconds for the database to warm up, and run the `dbConnect` call again.

More info in this blog post: https://blog.revolutionanalytics.com/2019/08/azure-sql-serverless.html . If you think this is an error in how Azure SQL Database responds to the connection request, let me know and I will pass that along to the Azure team.

**Comment by revodavid** [comment]
This is with the default "SQL Server" driver installed on Windows 10. I'm also testing with some other drivers (OBDC Driver 13 and Driver 17 for SQL Server) and will report back.

**Comment by revodavid** [comment]
Using [ODBC Driver 13 for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-2017#microsoft-odbc-driver-131-for-sql-server) generates the same error when the database is paused.

```R
> constr="
+ Driver={ODBC Driver 13 for SQL Server};Server=tcp:REDACTED.database.windows.net,1433;Database=retail;Uid=REDACTED@REDACTED;Pwd=REDACTED;Encrypt=yes;TrustServerCertificate=no;ConnectionTimeout=30;
+ "
> con <- dbConnect(odbc(), .connection_string=constr)
Error: nanodbc/nanodbc.cpp:950: 08001: [Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Timeout error [258]. 
```

**Comment by revodavid** [comment]
Same issue with ODBC Driver 17 for SQL Server.

**Comment by jotunskij** [comment]
Having this same issue with pyodbc after migrating some databases to Azure SQL Serverless:
`pyodbc.OperationalError: ('HYT00', '[HYT00] [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')`

**Comment by Matthewsre** [comment]
Getting this same result creating new connection with EF Core 2.2 on first attempt when paused. Second attempt shortly after will work.

**Comment by jimhester** [comment]
Hmm, I am not sure what we can do about this, if it takes a bit for the serverless server to start up after the first connection attempt, and that time is longer than the default login timeout I think we are kind of stuck...

**Comment by revodavid** [comment]
I tried various things to extend the timeout when setting up the connection -- if you can suggest the best way to do that I can give it a go.

**Comment by jimhester** [comment]
DId you try `con <- dbConnect(odbc(), .connection_string=constr, timeout = Inf)`? The odbc package defaults to a 10 second timeout, using `Inf` should make it never timeout.

**Comment by jordaniza** [comment]
Had this same issue and ended up transitioning away from serverless for the time being.

**Comment by smalgin** [comment]
Same issue. Since it's dev server, I decided to save money and ignore the annoyance. For Production mode I'll have to switch to Basic again. Pls fix.

**Comment by tyluRp** [comment]
I was experiencing this exact issue with a postgres database and `timeout = Inf` resolve it for me, e.g.
```r
con <- DBI::dbConnect(odbc::odbc(), "<my server>", timeout = Inf) 
```

**Comment by hilari0n** [comment]
What I see everywhere is that people only try on the "conservative" range of the connection timeout setting, e.g. 20-60 seconds. What I've read, is that the serverless database is expected to take over a minute to resume work after it is paused, so the connection timeout setting should be much more aggressive.
I would hesitate to use the `Inf` approach (i.e. no timeout) as it may cause your solution/application to hang indefinitely in case of network issues or the Azure service issues, but setting it to a couple of minutes (5-10) should be enough while staying on the semi-reasonable side.
Another approach, which should also conserve more resources is to introduce a retry. I.e. if a first connection attempt times out within a short / reasonable time (10-30 seconds), then the application should wait for a similar period of time and retry and repeat until it succeeds or when a 10 minute period is exceeded (since the first try was started).
