### ISSUE TITLE
Allow configuring the batch_size parameter 

### ISSUE THREAD

**Issue by andrewsali** [r-dbi/odbc#297]
We have observed that allowing to increase the batch_size parameter can have a dramatic impact on large inserts for Snowflake (https://github.com/r-dbi/odbc/blob/24bf73bc12286aeb75b3fee7023ce43fe01aee2a/src/odbc_result.cpp#L107)

Setting it to around 10,000 speeds up inserts by a factor of 10 for even medium datasets (100,000 rows).

Would it be possible to make this parameter user-configurable?

_Originally posted by @andrewsali in https://github.com/r-dbi/odbc/issues/34#issuecomment-524846076_

**Comment by jimhester** [comment]
You can now configure this with the `batch_rows` argument to `dbBind()` and `dbWriteTable()`.

**Comment by Microkiller** [comment]
Just wondering does this batch_rows controls how many rows that dbWriteTable() insert into the table every time. 

I am using dbWriteTable() without batch_rows. I notice it actually inserts one row every time and repeats the whole process until all the rows in the dataframe have been inserted. This causes huge delays for my case because I have a trigger which I expect to be triggered only once when I insert the data. But now it gets triggered as many times as the row number of my dataframe.

**Comment by Lydisis** [comment]
> Just wondering does this batch_rows controls how many rows that dbWriteTable() insert into the table every time.
> 
> I am using dbWriteTable() without batch_rows. I notice it actually inserts one row every time and repeats the whole process until all the rows in the dataframe have been inserted. This causes huge delays for my case because I have a trigger which I expect to be triggered only once when I insert the data. But now it gets triggered as many times as the row number of my dataframe.

Hi, apologies for resurrecting a closed issue to bump this question, but I am also plagued by the issue @Microkiller describes of each row seemingly being inserted one-by-one. If I understand correctly, updating the `batch_rows` parameter (i.e. to 10,000 as originally described in the FR) in `dbWriteTable()` can resolve this, correct?
