### ISSUE TITLE
SqlServer fails to write records that contain Inf values. 

### ISSUE THREAD

**Issue by shapenaji** [r-dbi/odbc#300]
Issue Description and Expected Result
`dbWriteTable` throws an error when trying to write records containing `Inf` values. 

this seems related to #6 and I accept that this may be out of scope. But posting this issue so that other users can find and understand what the following error means.

 ```nanodbc/nanodbc.cpp:1587: HY000: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.,  ```

### Database
Microsoft SQL Server Version: 13.00.5101

Example:
```r
con
#<OdbcConnection> Database@Location
# Database: Database
# Microsoft SQL Server Version: 13.00.5101
dbWriteTable(con, "tmpTestInf", data.frame(y = Inf))
# Error in result_insert_dataframe(rs@ptr, values) : 
```

**Comment by jimhester** [comment]
The issue is SQL Server (and it seems ODBC in general) does not support Infinity as a type. So our options would be throw an error, or change these to `NULL`.

While the existing error is not ideal, it does point you in the right direction, and thus far we have avoided trying to catch and rewrite error messages.

Preemptively scanning the data for `Inf` would hurt performance and trying to write tables with `Inf` should (I think) be fairly rare in practice.

So I think for now leaving the behavior as-is is the best alternative.

Thank you for opening the issue and sorry there is not a more satisfactory solution.
