### ISSUE TITLE
Error while inserting date column into oracle database using odbc package in R

### ISSUE THREAD

**Issue by sachalla1** [r-dbi/odbc#349]
we are using odbc connection to connect target database (oracle database) and we need to insert a dataframe into target database. We are using dbBind() to insert data frame into database. Please find the sample data and code mentioned below
```
Dataframe: Inputdata
  column1    column2    column3      date_column  column4
  <chr>      <chr>      <chr>        <chr>         <chr>
1 1111       6          fff          2015-11-01    MCA
2 2222       1          aaa          2006-12-02    NA
3 3333       2          bbb          2007-10-03    NA
4 4444       3          ccc          2008-01-04    NA
5 555        4          ddd          2007-11-05    NA
6 6666       5          eee          2010-11-06    BCH


R script :
Target1Conn<-dbConnect(odbc::odbc(), dsn = "TARGETDB", uid = "username", pwd = "password")
insert <- dbSendQuery(Target1Conn, paste0('insert into ', outputTableName, '(column1,column2,column3,date_column,column4) values(?,?,?,?,?)'))
dbBind(insert, list(InputData$column1,InputData$column2,InputData$column3,InputData$date_column,InputData$column4))"

Error:
Error in result_bind(res@ptr, as.list(params), batch_rows) :
  nanodbc/nanodbc.cpp:1617: 00000: [Oracle][ODBC][Ora]ORA-01861: literal does not match format string
```
My DataFrame has 1.3 million records and with the above approach after inserting 1024 records, the script is getting failed with error mentioned above.

if we ignore date column and insert data , we are able to insert data into database without any issues. Please let us know if any other solution is present.

**Comment by Mosk915** [comment]
I believe you're even able to insert the first 1024 rows is because `date_column` is a character column.  If you kept is as a date column, it would only work if your data frame was one row.

As a workaround, you can set `options(odbc.batch_rows = 1000000)` or to some other number of your choosing that is larger than the amount of rows in the data frame you need to insert.

Ideally this will be fixed to not requiring setting this option.

**Comment by Mosk915** [comment]
This has not been resolved.  This error occurs whenever the data frame has a date column and more than one row.

```
> dbWriteTable(conn = conn, name = "TEST_TABLE", value = data.frame(TIME = c(Sys.Date(), Sys.Date())))
Error in result_insert_dataframe(rs@ptr, values, batch_rows) : 
  nanodbc/nanodbc.cpp:1655: 00000: [Oracle][ODBC]Numeric value out of range.                                           [Oracle][ODBC]General error. ut of range.       
```

**Comment by jimhester** [comment]
That is a bug in the Oracle Driver, set `options(odbc.batch_rows = 1)` to work around it.

```r
con <- dbConnect(odbc::odbc(), "OracleODBC-19")
dbWriteTable(con, "test", data.frame(x = c(Sys.Date(), Sys.Date())), overwrite = TRUE)
dbReadTable(con, "test")
#>            x
#> 1 2020-10-22
#> 2 2020-10-22
```

**Comment by Mosk915** [comment]
This would cause reads and writes of large data frames to be extremely slow since it’s essentially looping through one row at a time.

If this is a bug with the Oracle driver, then wouldn’t it be expected to also be an issue when using the ROracle package?

**Comment by GuillaumePressiat** [comment]
Hi @jimhester,

Are there some improvements we can expect on this or not? Or not at all? 

dates in oracle database are quite common and useful.  I actually manage to_date(...) for all character dates columns in tables after integrations, it's quite complicated to accomplish.

odbc is really nice otherwise, but ROracle will be an answer for me in this case, if I can install it.

Thanks,
