### ISSUE TITLE
Parameterized query for SQL Server temp tables requires quoted inputs

### ISSUE THREAD

**Issue by nwstephens** [r-dbi/odbc#395]
I am having problems with parameterized queries and temp tables on SQL Server. I am using the RStudio Professional Driver for SQL Server. When I use unquoted inputs (e.g. 2 instead of "2") I get an error. When I use the quoted inputs (e.g. "2") I do not get an error and the table records the input as an integer. I do not get an error when using non-temp tables. I would expect the experience to be the same for temporary tables as non-temporary tables. In other words, I don't think I should have to quote numeric inputs ever.

```r
library(DBI) #v1.1.0
con <- dbConnect(odbc::odbc(), "SQL Server")

dbExecute(con, "create table ##tmp (x int)")

dbExecute(con, "insert into ##tmp (x) values (2)") # Does not throw error
dbExecute(con, "insert into ##tmp (x) values (?)", params = list("2")) # Does not throw error
dbExecute(con, "insert into ##tmp (x) values (?)", params = list(2)) # Throws error
```

Here is the error:

*Error in result_bind(res@ptr, as.list(params), batch_rows) : nanodbc/nanodbc.cpp:1617: 00000: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): The supplied length is not valid for data type nvarchar(max). Check the source data for invalid lengths. An example of an invalid length is data of nchar type with an odd length in bytes.*

There is a report that this issue does not occur with the Microsoft supplied driver (i.e. Not the RStudio driver). So this might be a driver issue. However, to avoid confusion, I've created this issue. I've also worked out the details of this issue in the following notebook:

https://colorado.rstudio.com/rsc/content/7389/sqlserver_temp_tables.nb.html

**Comment by bkt0031** [comment]
I'm seeing something very similar with using the odbc package against a MySQL database. If I run a parameterized query against an integer column in the database table using an integer in the params list I get no error and no data when do a dbFetch, but when I used it as a string, I get data:

```
> query <- DBI::dbSendQuery(db, "SELECT * FROM response_path_operations WHERE id_source = ?")
> DBI::dbBind(query, list(343846))
> dfOperations <- DBI::dbFetch(query)
> DBI::dbClearResult(query)
> nrow(dfOperations)
[1] 0
> query <- DBI::dbSendQuery(db, "SELECT * FROM response_path_operations WHERE id_source = ?")
> DBI::dbBind(query, list("343846"))
> dfOperations <- DBI::dbFetch(query)
> DBI::dbClearResult(query)
> nrow(dfOperations)
[1] 15
```

**Comment by bkt0031** [comment]
An update - I was just noodling around and if I specify the params value with as.integer() it works:
`> DBI::dbBind(query, list(as.integer(343846)))`

**Comment by simonpcouch** [comment]
I don't yet have credentials to test with the Pro Drivers, but can confirm that I don't see issues with the Microsoft driver. There have also been a number of SQL-specific changes since this issue was filed, which may play a role.

Also, I'd note that:

``` r
class(2)
#> [1] "numeric"
class(2L)
#> [1] "integer"
```

<sup>Created on 2024-03-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

So, it sounds passing an integer against an integer column works, but a numeric against an integer doesn't. That error message could be (much) more informative, but the odbc package currently isn't in the business of catching and rethrowing driver errors.

Since this seems more like a driver issue, and can be resolved by passing the correct data type, I'm going to go ahead and close.
