### ISSUE TITLE
dbAppendTable failes on temporary tables (SQL Server)

### ISSUE THREAD

**Issue by bwohl** [r-dbi/odbc#456]
### Issue Description and Expected Result
dbAppendTable checks that table exists, but dbExistsTable returns FALSE for temporary table.
Thus dbAppendTable fails for temporary tables
I think its this commit that introduced the problem.
Expected behaviour for me would be that dbExistsTable returns TRUE for also for temporary tables.

### Database
SQL Server 13.0.5888.11

### Reproducible Example
``` r
df <- data.frame(col1 <- c("test"))

sourceTable = paste0("##", do.call(paste0, replicate(7, sample(LETTERS, 1, TRUE), FALSE)))
DBI::dbCreateTable(con, sourceTable, df, temporary = TRUE)
DBI::dbExistsTable(con, sourceTable)
#> [1] FALSE
DBI::dbAppendTable(con, sourceTable, df)
#> Error in DBI::dbAppendTable(con, sourceTable, df): dbExistsTable(conn, name) is not TRUE
```

**Comment by detule** [comment]
Hey @bwohl 

Try using the full specification of the table.  For example:

```
DBI::dbExistsTable(conn, DBI::Id(catalog = "tempdb", schema = "dbo", table = sourceTable))
```

**Comment by awong234** [comment]
I had the same problem, and @detule 's suggestion worked, on Microsoft SQL Server Version: 13.00.5426. 

On DB2, however, this pattern works without having to specify the `DBI::Id`, for what it's worth.

**Comment by detule** [comment]
@awong234 for local temp tables ("single #"), IIRC part of the issue is that when you create a table "#foo", it is actually called something like "tempdb.dbo.#foo_________[randomized hash]".  If for some reason I really needed to use connection-local temp tables with SQL Server, that's what I would try: pairing DBI::Id with the "true" name of the local temp table that includes the hash appended by the server.

Cheers

**Comment by bwohl** [comment]
@detule sorry for the long wait, but I can confirm that you solution works. So I think this issue can be closed. Thank you for the input!
