### ISSUE TITLE
dbAppendTable doesn't return errors

### ISSUE THREAD

**Issue by lucazav** [r-dbi/odbc#465]
I'm inserting duplicated rows in a SQL Server table.
If I use `dbAppendTable`, I'm getting a meaningless "[0]" as result.
If I use `dbWriteTable` with `append = TRUE`, I'm getting the error that happened behind the scene:

> Error in result_insert_dataframe(rs@ptr, values) : 
>   nanodbc/nanodbc.cpp:1587: 23000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of PRIMARY KEY constraint 'PK__xxxxx'. Cannot insert duplicate key in object 'xxxxxxxxxx'. The duplicate key value is (xxxxxxxx).

It'd be useful also `dbAppendTable` will return errors.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.
