### ISSUE TITLE
Improve setup documentation

### ISSUE THREAD

**Issue by hadley** [r-dbi/odbc#565]
By creating some vignettes instead of trying to put everything in the readme

**Comment by detule** [comment]
Adding a note here:

In addition, since at this point `unixODBC` is the de-facto [required](https://github.com/r-dbi/odbc/blob/ea2b935e475f4b5361bf1cdc1f41efbaba0db051/README.md?plain=1#L73) [driver](https://github.com/r-dbi/odbc/blob/ea2b935e475f4b5361bf1cdc1f41efbaba0db051/README.md?plain=1#L107) [manager](https://github.com/r-dbi/odbc/blob/ea2b935e475f4b5361bf1cdc1f41efbaba0db051/README.md?plain=1#L49), on `Linux` and on `MacOs` can we provide a wrapper to `odbcinst -j` that will read/off the location of the driver/data-source configuration files?

**Comment by hadley** [comment]
And presumably on windows it's either a hard coded path or available in the registry?
