### ISSUE TITLE
Connection from RStudio to Snowflake throws error about odbcListObjects

### ISSUE THREAD

**Issue by ronblum** [r-dbi/odbc#780]
This is a problem in the development version of `odbc` when making a connection from RStudio to Snowflake. This works correctly in the  current version of `odbc`, 1.4.2.

1. In RStudio Desktop Pro, install the `odbc` version being developed for Snowflake: `pak::pak("r-dbi/odbc#662")`
2. In the Connections Pane, create use the New Connection wizard to install the Snowflake driver if it's not already installed.
3. Connect to Snowflake using `DBI` and `odbc::odbc` (not `odbc::snowflake`).
    - When the connection is successful, the Connections Pane is empty and the following error appears in a popup and the Console.
``` 
Error in UseMethod("odbcListObjects") : 
  no applicable method for 'odbcListObjects' applied to an object of class "Snowflake"
```

**Comment by simonpcouch** [comment]
Awesome, glad that that did the trick.

In general, it's possible that in the time since 662 was branched off from the main dev version we'd work on other snowflake-relevant changes that weren't "backported" to 662. 662 was merged upstream a couple weeks ago, though, and I'm not sure that there have been any relevant changes that would affect that dispatch since then, so I'm tempted to think a dependency update or change in your local dev environment is more likely to be responsible for that change in output—hard to say without more info!

**Comment by ronblum** [comment]
Cool, thanks for the explanation!
