### ISSUE TITLE
driver-snowflake: Class confusion

### ISSUE THREAD

**Issue by detule** [r-dbi/odbc#861]
We have

```
setClass("Snowflake", contains = "OdbcConnection")
...
snowflake <- function() {
  new("Snowflake")
}
...
setMethod(
  "dbConnect", "Snowflake",
   function(drv,
```

but the `DBI::dbConnect` API is formulated relative to `OdbcDriver`, not `OdbcConnection`.  I don't think this is causing issues, *right now*, however if nobody objects, i plan on changing the `snowflake()` call to return an object that inherits from `OdbcDriver`.  This will also align the `Snowflake` and `Databricks` API.

**Comment by simonpcouch** [comment]
Ah, interesting. Nice catch! Just talking myself through this:

**Backends that don't have a connection helper** just have e.g. `setClass("DBMSName", contains = "OdbcConnection")` which kicks in from `dbConnect(odbc())` output and the methods are inherited via `DBMSName`. **The _driver_ class is generic to `odbc()`, the _connection_ class is DBMS-specific.**

**Databricks** has `databricks()` which returns an `DatabricksOdbcDriver < OdbcDriver`. A `dbConnect()` method is defined relative to it, otherwise Databricks just inherits its methods from `setClass("Spark SQL", contains = "OdbcConnection")` (i.e. based on the output of `dbConnect()`). **The _driver_ class is DBMS-specific, the _connection_ class kind of is** even though it doesn't use the DBMS name explicitly.

**Snowflake** has `snowflake()` which returns a `new("Snowflake")` as `setClass("Snowflake", contains = "OdbcConnection")`. The resulting connection object from `dbConnect()` _also_ has class `"Snowflake"` and methods are defined relative to that class. **The _driver_ and _connection_ classes are DBMS-specific but, unfortunately, identical.** We can thus split off the driver class to be DBMS-specific but also be disambiguated from the connection class.

So we do make `snowflake()` return `new("SnowflakeOdbcDriver")` which is just `setClass("SnowflakeOdbcDriver", contains = "OdbcDriver")`, as you suggest, and transition `dbConnect` from working on `Snowflake` instead to `SnowflakeOdbcDriver`, but then keep all of the existing "Snowflake" class and methods code as-is, since it defines behavior on the connection rather than the driver?
